### ISSUE TITLE
jekyll 3.4.0 | Error:  765: unexpected token at ''

### ISSUE THREAD

**Issue by bpmottathai** [JustinAiken/jekyll-gitlab-letsencrypt#20]
```
Traceback (most recent call last):
	15: from /usr/local/bin/jekyll:23:in `<main>'
	14: from /usr/local/bin/jekyll:23:in `load'
	13: from /var/lib/gems/2.5.0/gems/jekyll-3.4.0/exe/jekyll:13:in `<top (required)>'
	12: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	11: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	10: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	 9: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	 8: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	 7: from /var/lib/gems/2.5.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/commands/gitlab/letsencrypt.rb:10:in `block (2 levels) in init_with_program'
	 6: from /var/lib/gems/2.5.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:12:in `process!'
	 5: from /var/lib/gems/2.5.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:24:in `process!'
	 4: from /var/lib/gems/2.5.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:40:in `commit_to_gitlab!'
	 3: from /var/lib/gems/2.5.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/gitlab_client.rb:14:in `commit!'
	 2: from /var/lib/gems/2.5.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/gitlab_client.rb:59:in `branch_exists?'
	 1: from /usr/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)

```

**Comment by JustinAiken** [comment]
> `jekyll-gitlab-letsencrypt-0.2.0`

That version is old... try `bundle update jekyll-gitlab-letsencrypt` to get up to 0.3.1 - it has fixes for Gitlab's new API
