### ISSUE TITLE
Possible namespace parsing error

### ISSUE THREAD

**Issue by japorized** [JustinAiken/jekyll-gitlab-letsencrypt#24]
Hi there,

I am getting the following error:

```
jekyll 3.8.5 | Error:  Failed response for projects/japorized%2fTeX_notes. Please check if personal token and repo name are correct
```

Here's the stack trace (from `--trace`):

```
Traceback (most recent call last):
	14: from /home/japorized/.gem/bin/jekyll:23:in `<main>'
	13: from /home/japorized/.gem/bin/jekyll:23:in `load'
	12: from /home/japorized/.gem/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
	11: from /home/japorized/.gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	10: from /home/japorized/.gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	 9: from /home/japorized/.gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	 8: from /home/japorized/.gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	 7: from /home/japorized/.gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	 6: from /home/japorized/.gem/gems/jekyll-gitlab-letsencrypt-0.4.1/lib/jekyll/commands/gitlab/letsencrypt.rb:10:in `block (2 levels) in init_with_program'
	 5: from /home/japorized/.gem/gems/jekyll-gitlab-letsencrypt-0.4.1/lib/jekyll/gitlab/letsencrypt/process.rb:12:in `process!'
	 4: from /home/japorized/.gem/gems/jekyll-gitlab-letsencrypt-0.4.1/lib/jekyll/gitlab/letsencrypt/process.rb:24:in `process!'
	 3: from /home/japorized/.gem/gems/jekyll-gitlab-letsencrypt-0.4.1/lib/jekyll/gitlab/letsencrypt/process.rb:42:in `commit_to_gitlab!'
	 2: from /home/japorized/.gem/gems/jekyll-gitlab-letsencrypt-0.4.1/lib/jekyll/gitlab/letsencrypt/gitlab_client.rb:14:in `commit!'
	 1: from /home/japorized/.gem/gems/jekyll-gitlab-letsencrypt-0.4.1/lib/jekyll/gitlab/letsencrypt/gitlab_client.rb:57:in `branch_exists?'
/home/japorized/.gem/gems/jekyll-gitlab-letsencrypt-0.4.1/lib/jekyll/gitlab/letsencrypt/gitlab_client.rb:75:in `repo_id': Failed response for projects/japorized%2fTeX_notes. Please check if personal token and repo name are correct (StandardError)
```

Not too sure what went wrong here, but is seems like my namespace identifier is being recognized as `projects/<gitlab_repo>` instead of just `<gitlab_repo>`, where `<gitlab_repo>` is the specified setting in `_config.yml`.

**Comment by japorized** [comment]
This is somewhat awkward. I made sure a number of times that my token was correct and I still had that error. Recreated a new token and now it's working. I shall close the issue.

**Comment by JustinAiken** [comment]
Odd, but glad it works now!
